<?php

namespace App\Traits;

use Illuminate\Http\Response;

trait ApiResponser
{
    protected function successResponse($data, $code = Response::HTTP_OK)
    {
        return response($data, $code)->header('Content-Type', 'application/json');
    }

    // error response generated by api gateway itself
    protected function errorResponse($message, $code)
    {
        return response()->json(['error' => $message, 'code' => $code], $code);
    }

    // Add Error Message return by API gateway request
    // Add errorMessage will return message generate by our API’s
    protected function errorMessage($message, $code)
    {
        return response($message, $code)->header('Content-Type', 'application/json');
    }
}